nelmio_api_doc:
    documentation:
        info:
            title: Bilemo
            description: Bilemo API
            version: 2.0.0
        paths:
            /api/login_check:
                post:
                    operationId: postCredentialsItem
                    tags:
                        - Client
                    summary: Create a new JWT token
                    requestBody:
                        description: Create a new JWT token
                        content:
                            application/json:
                                schema:
                                    $ref: '#/components/schemas/Credentials'
                    responses:
                        '200':
                            description: Return a new JWT token
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/Token'
        components:
            schemas:
                Token:
                    type: object
                    properties:
                        token:
                            type: string
                            readOnly: true
                Credentials:
                    type: object
                    properties:
                        email:
                            type: string
                            default: tania08082000@gmail.com
                        password:
                            type: string
                            default: admin123
            securitySchemes:
                bearerAuth:
                    type: apiKey
                    in: header
                    name: Authorization
        security:
            - bearerAuth: []

    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc.json$) # Accepts routes under /api except /api/doc