version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    environment:
      POSTGRES_DB: bilemo
      # You should definitely change the password in production
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
    ports:
      - "5434:5432"
###< doctrine/doctrine-bundle ###
